language: android

android:
  components:
    - build-tools-27.0.3
    - android-27

licenses:
  - '.+'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
  - yes | sdkmanager "platforms;android-27"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
