before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect

script:
  - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip sdk-tools-linux-3859397.zip
  - export ANDROID_HOME=${PWD}
  - ./init.sh
  - cd app
  - ./gradlew assembleRelease
