name: Build APKs
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Linux machine is required because of Buildroot dependency
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Assemble release APKs
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleRelease
          build-root-directory: app
          wrapper-directory: app
      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: app/build/outputs/apk/release/*.apk
